USE Sokoni
GO
--PRODUCTS TABLE--
CREATE TABLE Products(
    ProductId VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    ImageUrl VARCHAR(MAX) NOT NULL ,
    Price DECIMAL(18, 2) NOT NULL,
    Description VARCHAR(MAX) NOT NULL,
    Stock INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT GETDATE()
);
USE Sokoni
GO
--USERS TABLE--

CREATE TABLE Users (
    UserId VARCHAR(255) PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL DEFAULT 'User',
    CreatedAt DATETIME2 DEFAULT GETDATE()
);
